### ISSUE TITLE
faced an unhandled "error" even

### ISSUE THREAD

**Issue by alioualarbi** [fredsted/webhook.site#78]

**Comment by alioualarbi** [comment]
Thanks for sharing i want to test this webhook for incoming https request, but when tried to build the Dockerfile i did face this error :

[03:41:48] gulp-notify: [Laravel Elixir] Sass Compiled!
[03:41:48] gulp-notify: [Error in notifier] Error in plugin 'gulp-notify'
Message:
    not found: notify-send
Details:
    code: ENOENT
[03:41:48] Finished 'sass' after 3.94 s
[03:41:48] Starting 'browserify'...

Fetching Browserify Source Files...
   - resources/assets/js/libs.js


Saving To...
   - public/js/libs.js

[03:41:58] gulp-notify: [Laravel Elixir] Browserify Compiled!
[03:41:58] gulp-notify: [Error in notifier] Error in plugin 'gulp-notify'
Message:
    notify-send must be installed on the system.
[03:41:58] Finished 'browserify' after 10 s
[03:41:58] Starting 'browserify'...
   - resources/assets/js/app.js


Saving To...
   - public/js/bundle.js


events.js:183
      throw er; // Unhandled 'error' event
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)
    at unexpected (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2103:9)
    at semicolon (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2123:56)
    at simple_statement (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2314:73)
    at eval (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2183:19)
    at eval (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)
    at block_ (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2429:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ gulp: `gulp --production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ gulp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-08T03_42_00_213Z-debug.log
The command '/bin/sh -c npm run gulp' returned a non-zero code: 1

I'm not sure where the issue is located or if there is a syntaxe error.

**Comment by fredsted** [comment]
have you tried this

https://stackoverflow.com/questions/31431503/gulp-notify-error-in-notifier-error-in-plugin-gulp-notify-not-found-notify
